# Site settings
title: Kõnele
email: kaljurand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Kõnele is an Android app that offers speech-to-text services to other apps.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: Kaljurand

# Build settings
markdown: kramdown
